// <auto-generated />
namespace MovieCom.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class LastModifiedRemoved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LastModifiedRemoved));
        
        string IMigrationMetadata.Id
        {
            get { return "201808021050143_LastModifiedRemoved"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
